general {
    grace = 5
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/omar/Downloads/purple-desert-night-city-1b-2560x1440.jpg
    blur_passes = 2
    blur_size = 4
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.15
    outer_color = rgba(8ccff0ff)
    inner_color = rgba(0f1417ff)
    font_color = rgba(dfe3e7ff)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    fail_color = rgba(ffb4abff)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba(c7c2eaff)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(dfe3e7ff)
    font_size = 72
    font_family = Sans Bold
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgba(c0c8cdff)
    font_size = 18
    font_family = Sans
    position = 0, 60
    halign = center
    valign = center
}
