# --- Starship prompt ---
eval "$(starship init zsh)"

# --- rbenv ---
export RBENV_ROOT="$HOME/.rbenv"
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init - zsh)"

# Use plugins in ~/.zsh/plugins
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History settings
HISTFILE="$HOME/.config/zsh/history"
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory  

# Aliases
# git
alias ga='git add'
alias gap='ga --patch'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gn='git checkout -b'
alias gp='git push'
alias gu='git pull'
alias gd='git diff --output-indicator-new=" " --output-indicator-old=" "'
alias gst='git status --short'
alias gf='git fetch'
gcm() { git commit --message "$*" }

# Eza
alias ls="eza --icons"
alias ll="eza -lah --icons"

# programs
alias zen='nohup zen-browser >/dev/null 2>&1 &'

